# Generated by Django 3.2.9 on 2021-12-06 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutuberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sub_title', models.CharField(max_length=40)),
                ('list_activated', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('my_youtuber_list_activated', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(blank=True, related_name='My_Youtuber_list', to=settings.AUTH_USER_MODEL)),
                ('youtuber', models.ManyToManyField(related_name='Youtuber_list', to='youtuber.Youtuber')),
            ],
        ),
    ]
