# Generated by Django 3.2.9 on 2021-12-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtuber', '0002_youtuberlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuberlist',
            old_name='name',
            new_name='main_title',
        ),
    ]
