# Generated by Django 3.2.9 on 2021-12-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtuber', '0003_rename_name_youtuberlist_main_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuberlist',
            old_name='youtuber',
            new_name='youtubers',
        ),
    ]
