# Generated by Django 3.2.9 on 2021-12-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtuber', '0004_rename_youtuber_youtuberlist_youtubers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuberlist',
            name='youtubers',
            field=models.ManyToManyField(related_name='youtuber_list', to='youtuber.Youtuber'),
        ),
    ]
